version: '3'

services:

  jenkins:
    build: ./Jenkins
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - jenkins:/var/jenkins_home/:rw
      - mvnrepo:/root/.m2/repository/:rw

  postgres:
    image: postgres:10.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/sonarqube
      POSTGRES_DB: sonarqube
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:6.7.1
    environment:
        SONARQUBE_JDBC_USERNAME: admin
        SONARQUBE_JDBC_PASSWORD: password
        SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    restart: always
    depends_on:
      - postgres
  
volumes:
    jenkins:
    postgres:
    mvnrepo: